version: '2'

services:
  api:
    build:
      context: ./services
      dockerfile: ./api/Dockerfile
    image: scrum-disaster/api
    links:
      - score
    labels:
      container_group: service
    environment:
      REMOVE_LOG: "${REMOVE_LOG}"
      INTERACTIVE: "${INTERACTIVE}"
      YODIZ_API_KEY: "${YODIZ_API_KEY}"
  web:
    build:
      context: ./services
      dockerfile: ./web/Dockerfile
    image: scrum-disaster/web
    links:
      - api
    labels:
      container_group: service
    environment:
      REMOVE_LOG: "${REMOVE_LOG}"
      INTERACTIVE: "${INTERACTIVE}"
  score:
    build:
      context: ./services
      dockerfile: ./score/Dockerfile
    image: scrum-disaster/score
    labels:
      container_group: service
    environment:
      INTERACTIVE: "${INTERACTIVE}"
