version: '2'

services:
  api:
    environment:
      NODE_ENV: development
    entrypoint: /home/docker/startup.integration.sh
    networks:
      - default
      - scrum-disaster
networks:
  scrum-disaster:
    driver: bridge
